# Generated by Django 5.0.2 on 2025-07-05 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Goal name/description', max_length=200)),
                ('area', models.CharField(choices=[('physical', 'Physical'), ('technical', 'Technical'), ('tactical', 'Tactical'), ('mental', 'Mental')], default='technical', max_length=20)),
                ('timeframe', models.CharField(choices=[('short_term', 'Short Term'), ('medium_term', 'Medium Term'), ('long_term', 'Long Term')], default='medium_term', max_length=20)),
                ('progress', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('good_progress', 'Good Progress'), ('excellent_progress', 'Excellent Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the goal')),
                ('target_date', models.DateField(blank=True, help_text='Target completion date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_goals', to='core.coach')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.player')),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
                'ordering': ['-created_at'],
            },
        ),
    ]
