# Generated by Django 5.0.2 on 2025-07-09 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Process goal name/description', max_length=200)),
                ('progress', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('good_progress', 'Good Progress'), ('excellent_progress', 'Excellent Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the process goal')),
                ('target_date', models.DateField(blank=True, help_text='Target completion date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the process goal')),
                ('main_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_goals', to='core.goal')),
            ],
            options={
                'verbose_name': 'Process Goal',
                'verbose_name_plural': 'Process Goals',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
